name: CI

# Specify the Github events which triggers a CI build
on: push

# Now define a job called 'build'
jobs:

  build:

    # Specify the OS to run tests on
    runs-on: ubuntu-latest

    # Write the sequence of steps for the job
    steps:

      # First: checkout the repo
      # The name is an optional label which shows up in the log
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install -e .
      
      - name: Test with PyTest
        run: |
         pytest --cov=inflammation.models tests/test_models.py

