name: CI

# Specify the Github events which triggers a CI build
on: push

# Now define a job called 'build'
jobs:

  build:

    # Specify the OS to run tests on
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows.latest]
        python-version: [3.8, 3.9, 3.10]

    # Write the sequence of steps for the job
    steps:

      # First: checkout the repo
      # The name is an optional label which shows up in the log
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install -e .
      
      - name: Test with PyTest
        run: |
         pytest --cov=inflammation.models tests/test_models.py

